---
micronaut:
    application:
        name: my-stat-mn
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
            logout:
                enabled: true
        session:
            enabled: true
            login-failure-target-url: /login/authFailed
            forbidden-target-url: /forbidden
            unauthorized-target-url: /unauthorized
# micronaut.views.velocity.enabled: true
---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 1
---
micronaut:
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
---
mongodb:
    uri: mongodb://localhost:27117/mystat
---
datasources:
    default:
        url: jdbc:postgresql://localhost:5432/mystat
        username: mystat
        password: pass
        
---
redis:
    uri: redis://localhost
    caches:
        user:
            expire-after-write: 1h